### ISSUE TITLE
Support POST requests in webpack dev server

### ISSUE THREAD

**Issue by deveth0** [pro-vision/fe-tools#19]
For some projects it might be useful, if the webpack dev server would also be able to accept POST requests (and just redirect them to the GET request, so static resources can still be used).
There is an interesting solution here, what do you think?
https://stackoverflow.com/questions/47442543/how-do-i-get-webpack-dev-server-to-accept-post-requests

Background: when developing an application, that will use a backend on production which requires POST requests, those requests currently can't be faked on the dev server. An option is to check in the code, if we are running on production or dev and then switch between POST and GET, but this kinda sucks...

**Comment by friewerts** [comment]
i think this is a very special use-case which can be handled by using a custom webpack.config.dev.js, by now.

**Comment by mbehzad** [comment]
indeed this **is** our solution in different projects:
```
   // devServerConfig / Settings
   before: (app, _server) => {
      app.use((request, _response, next) => {
        request.method = "GET";

        return next();
      });
    }
```
