### ISSUE TITLE
`assets` option from the old stylemark is missing in the new stylemark

### ISSUE THREAD

**Issue by mbehzad** [pro-vision/fe-tools#230]
`lsgAssetsSrc` was removed with the note: "... pv-scripts users can just use the resources folder". The issue with that is that the resource directory is [meant](https://experienceleague.adobe.com/en/docs/experience-manager-65/content/implementing/developing/introduction/clientlibs#locating-a-client-library-folder-and-using-the-proxy-client-libraries-servlet) to be part of the clientLibraries and will be deployed to the production. And shouldn't contain styleguide specific content.
PR #226 will add the stylemark's `assests` option back, which can be used for any icons, css, etc that is needed only for the styleguide.

**Comment by friewerts** [comment]
see comment in PR
