### ISSUE TITLE
PreCommit Hooks, Travis and Conventional Commits

### ISSUE THREAD

**Issue by ifahrentholz** [pro-vision/fe-tools#6]
1. To improve code qualitiy we want to introduce precommit hooks.
2. To simplify releases we want to introduce automatic testing with travis ci
3. Introduce auto releases via travis, lerna and conventional commits (https://www.conventionalcommits.org)

**Comment by friewerts** [comment]
1.) and 3.) are done in #56 . 2.) should be part of a specific Issue.
